'use client';

export default function MapLegend() {
  return (
    <div style={{
      position: 'absolute',
      bottom: '16px',
      left: '16px',
      background: 'var(--s-panel, #1f2937)',
      borderRadius: '8px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
      border: '1px solid var(--s-border, #374151)',
      padding: '16px',
      zIndex: 1000,
      minWidth: '240px',
      maxWidth: '280px'
    }}>
      <div style={{
        fontSize: '14px',
        fontWeight: 600,
        marginBottom: '12px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        color: 'var(--s-text, #f9fafb)'
      }}>
        Expansion Suggestions
        <div
          title="All expansion points are generated by Subway AI. Colour intensity reflects confidence and data completeness."
          style={{
            width: '16px',
            height: '16px',
            borderRadius: '50%',
            background: 'var(--s-accent, #00a862)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '11px',
            fontWeight: 700,
            color: 'white',
            cursor: 'help'
          }}
        >
          ?
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {/* HIGH */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '14px',
            height: '14px',
            borderRadius: '50%',
            background: '#14b8a6',
            border: '2px solid var(--s-panel, #1f2937)',
            boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
            flexShrink: 0
          }} />
          <span style={{ 
            fontSize: '13px',
            color: 'var(--s-text, #f9fafb)',
            lineHeight: '1.3'
          }}>
            High confidence
          </span>
        </div>

        {/* MEDIUM */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '14px',
            height: '14px',
            borderRadius: '50%',
            background: '#a855f7',
            border: '2px solid var(--s-panel, #1f2937)',
            boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
            flexShrink: 0
          }} />
          <span style={{ 
            fontSize: '13px',
            color: 'var(--s-text, #f9fafb)',
            lineHeight: '1.3'
          }}>
            Medium confidence
          </span>
        </div>

        {/* LOW */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '14px',
            height: '14px',
            borderRadius: '50%',
            background: '#92400e',
            border: '2px solid var(--s-panel, #1f2937)',
            boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
            flexShrink: 0
          }} />
          <span style={{ 
            fontSize: '13px',
            color: 'var(--s-text, #f9fafb)',
            lineHeight: '1.3'
          }}>
            Low confidence
          </span>
        </div>

        {/* INSUFFICIENT_DATA */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '14px',
            height: '14px',
            borderRadius: '50%',
            background: '#6b7280',
            border: '2px solid var(--s-panel, #1f2937)',
            boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
            flexShrink: 0
          }} />
          <span style={{ 
            fontSize: '13px',
            color: 'var(--s-text, #f9fafb)',
            lineHeight: '1.3'
          }}>
            Insufficient data
          </span>
        </div>
      </div>

      <div style={{
        marginTop: '12px',
        paddingTop: '12px',
        borderTop: '1px solid var(--s-border, #374151)',
        fontSize: '11px',
        color: 'var(--s-muted, #9ca3af)',
        lineHeight: '1.5'
      }}>
        <span style={{ color: 'var(--s-accent, #00a862)' }}>●</span> AI-generated expansion opportunities
      </div>
    </div>
  );
}
